version: '3'

services:
    web:
        build: .
        ports:
          - "5000:5000"

    db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql:rw
       - ./db-init:/docker-entrypoint-initdb.d/:rw
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: data
       MYSQL_USER: root
       MYSQL_PASSWORD: password

volumes:
    db_data: 
