---
- name: Provision AWS Instances
  become: true
  hosts: localhost 
  roles:
    - { role: provision-vpc }
    - { role: provision-ec2 }
  
- name: Provision EC2 instance
  become: true
  hosts: server

  roles:
    - { role: docker }
 



